-- BlueHarbor Phase 2: documentation and compliance. Run after scripts 01-04.
-- Safe to rerun; existing operational and buyer data is preserved.
BEGIN;
SET search_path TO blueharbor, public;

CREATE TABLE IF NOT EXISTS compliance_rule_sets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country TEXT NOT NULL,
  product_category TEXT NOT NULL DEFAULT '*',
  requirement_code TEXT NOT NULL,
  document_name TEXT NOT NULL,
  issuer TEXT NOT NULL,
  buyer_owned INTEGER NOT NULL DEFAULT 0 CHECK (buyer_owned IN (0,1)),
  blocking INTEGER NOT NULL DEFAULT 1 CHECK (blocking IN (0,1)),
  lead_days INTEGER NOT NULL DEFAULT 0 CHECK (lead_days BETWEEN 0 AND 365),
  source_url TEXT NOT NULL,
  reviewed_on TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
  version INTEGER NOT NULL DEFAULT 1,
  updated TEXT NOT NULL DEFAULT '',
  UNIQUE(country,product_category,requirement_code)
);

CREATE TABLE IF NOT EXISTS exporter_credentials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  authority TEXT NOT NULL,
  number TEXT NOT NULL,
  scope TEXT NOT NULL,
  issued TEXT NOT NULL DEFAULT '',
  expires TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  notes TEXT NOT NULL DEFAULT '',
  updated TEXT NOT NULL DEFAULT '',
  UNIQUE(name,number)
);

CREATE TABLE IF NOT EXISTS order_document_requirements (
  order_id TEXT NOT NULL REFERENCES orders(id),
  requirement_code TEXT NOT NULL,
  document_name TEXT NOT NULL,
  owner TEXT NOT NULL CHECK (owner IN ('BUYER','EXPORTER')),
  blocking INTEGER NOT NULL DEFAULT 1 CHECK (blocking IN (0,1)),
  status TEXT NOT NULL DEFAULT 'WAITING',
  due_date TEXT NOT NULL DEFAULT '',
  source_rule_id BIGINT REFERENCES compliance_rule_sets(id),
  note TEXT NOT NULL DEFAULT '',
  updated TEXT NOT NULL DEFAULT '',
  PRIMARY KEY(order_id,requirement_code)
);

ALTER TABLE trade_documents ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'DRAFT';
ALTER TABLE trade_documents ADD COLUMN IF NOT EXISTS issuer TEXT NOT NULL DEFAULT '';
ALTER TABLE trade_documents ADD COLUMN IF NOT EXISTS document_number TEXT NOT NULL DEFAULT '';
ALTER TABLE trade_documents ADD COLUMN IF NOT EXISTS issue_date TEXT NOT NULL DEFAULT '';
ALTER TABLE trade_documents ADD COLUMN IF NOT EXISTS expiry_date TEXT NOT NULL DEFAULT '';

INSERT INTO compliance_rule_sets(country,product_category,requirement_code,document_name,issuer,buyer_owned,blocking,lead_days,source_url,reviewed_on,updated) VALUES
('*','*','COMMERCIAL_INVOICE','Commercial Invoice','BlueHarbor Export Desk',0,1,2,'https://www.dgft.gov.in/','2026-09-10','2026-09-10'),
('*','*','PACKING_LIST','Packing List','BlueHarbor Export Desk',0,1,2,'https://www.dgft.gov.in/','2026-09-10','2026-09-10'),
('*','*','SHIPPING_BILL','Shipping Bill','Indian Customs / ICEGATE',0,1,3,'https://www.icegate.gov.in/','2026-09-10','2026-09-10'),
('*','*','TRANSPORT_DOCUMENT','Bill of Lading / Air Waybill','Carrier',0,1,1,'https://www.dgft.gov.in/','2026-09-10','2026-09-10'),
('*','*','CFE','Certificate for Export','Export Inspection Council / Agency',0,1,5,'https://www.eicindia.gov.in/','2026-09-10','2026-09-10'),
('*','*','HEALTH_CERTIFICATE','Health Certificate','Competent Authority',0,1,5,'https://www.eicindia.gov.in/','2026-09-10','2026-09-10'),
('United States','*','FDA_PRIOR_NOTICE','FDA Prior Notice Confirmation','US FDA',1,1,2,'https://www.fda.gov/industry/fda-import-process/prior-notice-imported-foods','2026-09-10','2026-09-10'),
('United States','*','IMPORTER_VERIFICATION','Seafood HACCP Importer Verification','US Importer',1,1,7,'https://www.fda.gov/food/importing-food-products-united-states/imported-seafood-safety-program','2026-09-10','2026-09-10'),
('Germany','*','EU_CHEDP','TRACES CHED-P Reference','EU Importer / Border Control Post',1,1,3,'https://food.ec.europa.eu/horizontal-topics/traces/modules_en','2026-09-10','2026-09-10'),
('France','*','EU_CHEDP','TRACES CHED-P Reference','EU Importer / Border Control Post',1,1,3,'https://food.ec.europa.eu/horizontal-topics/traces/modules_en','2026-09-10','2026-09-10'),
('Netherlands','*','EU_CHEDP','TRACES CHED-P Reference','EU Importer / Border Control Post',1,1,3,'https://food.ec.europa.eu/horizontal-topics/traces/modules_en','2026-09-10','2026-09-10')
ON CONFLICT(country,product_category,requirement_code) DO NOTHING;

REVOKE ALL ON compliance_rule_sets,exporter_credentials,order_document_requirements FROM PUBLIC,anon,authenticated;
REVOKE ALL ON SEQUENCE compliance_rule_sets_id_seq,exporter_credentials_id_seq FROM PUBLIC,anon,authenticated;
COMMIT;
