-- BlueHarbor Phase 3: shipping, customs and live-tracking foundation foundation. Run after 06.
BEGIN;
SET search_path TO blueharbor, public;

CREATE TABLE IF NOT EXISTS transport_shipments (
 id TEXT PRIMARY KEY, booking_reference TEXT NOT NULL DEFAULT '', mode TEXT NOT NULL DEFAULT 'OCEAN',
 carrier TEXT NOT NULL DEFAULT '', vessel TEXT NOT NULL DEFAULT '', voyage TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'PLANNING',
 origin_port TEXT NOT NULL, destination_port TEXT NOT NULL, origin_lat DOUBLE PRECISION, origin_lon DOUBLE PRECISION,
 destination_lat DOUBLE PRECISION, destination_lon DOUBLE PRECISION, planned_departure TEXT NOT NULL DEFAULT '', actual_departure TEXT NOT NULL DEFAULT '',
 planned_arrival TEXT NOT NULL DEFAULT '', actual_arrival TEXT NOT NULL DEFAULT '', booking_cutoff TEXT NOT NULL DEFAULT '', documentation_cutoff TEXT NOT NULL DEFAULT '',
 vgm_cutoff TEXT NOT NULL DEFAULT '', shipping_instructions TEXT NOT NULL DEFAULT '', created TEXT NOT NULL, updated TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS shipment_orders (
 shipment_id TEXT NOT NULL REFERENCES transport_shipments(id), order_id TEXT NOT NULL UNIQUE REFERENCES orders(id), created TEXT NOT NULL,
 PRIMARY KEY(shipment_id,order_id)
);
CREATE TABLE IF NOT EXISTS transport_legs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, shipment_id TEXT NOT NULL REFERENCES transport_shipments(id), sequence INTEGER NOT NULL,
 mode TEXT NOT NULL DEFAULT 'VESSEL', carrier TEXT NOT NULL DEFAULT '', vessel TEXT NOT NULL DEFAULT '', voyage TEXT NOT NULL DEFAULT '',
 origin_name TEXT NOT NULL, origin_lat DOUBLE PRECISION, origin_lon DOUBLE PRECISION, destination_name TEXT NOT NULL,
 destination_lat DOUBLE PRECISION, destination_lon DOUBLE PRECISION, planned_departure TEXT NOT NULL DEFAULT '', actual_departure TEXT NOT NULL DEFAULT '',
 planned_arrival TEXT NOT NULL DEFAULT '', actual_arrival TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'PLANNED', UNIQUE(shipment_id,sequence)
);
CREATE TABLE IF NOT EXISTS shipment_containers (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, shipment_id TEXT NOT NULL REFERENCES transport_shipments(id), container_number TEXT NOT NULL UNIQUE,
 container_type TEXT NOT NULL DEFAULT '40RF', seal_number TEXT NOT NULL DEFAULT '', stuffing_status TEXT NOT NULL DEFAULT 'PLANNED',
 stuffed_at TEXT NOT NULL DEFAULT '', reefer_setpoint DOUBLE PRECISION, ventilation_cbm DOUBLE PRECISION, humidity_percent DOUBLE PRECISION,
 tare_kg INTEGER NOT NULL DEFAULT 0, verified_gross_kg INTEGER NOT NULL DEFAULT 0, vgm_method TEXT NOT NULL DEFAULT '',
 vgm_party TEXT NOT NULL DEFAULT '', vgm_reference TEXT NOT NULL DEFAULT '', vgm_at TEXT NOT NULL DEFAULT '', updated TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS carrier_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, shipment_id TEXT NOT NULL REFERENCES transport_shipments(id), container_id BIGINT REFERENCES shipment_containers(id),
 event_code TEXT NOT NULL, event_label TEXT NOT NULL, event_type TEXT NOT NULL CHECK(event_type IN ('ESTIMATED','ACTUAL')),
 occurred_at TEXT NOT NULL, location_name TEXT NOT NULL, latitude DOUBLE PRECISION, longitude DOUBLE PRECISION,
 source_type TEXT NOT NULL CHECK(source_type IN ('STAFF','CARRIER','CUSTOMS','SENSOR')), source_provider TEXT NOT NULL DEFAULT 'BlueHarbor staff',
 external_event_id TEXT, received_at TEXT NOT NULL, note TEXT NOT NULL DEFAULT '', UNIQUE(source_provider,external_event_id)
);
CREATE TABLE IF NOT EXISTS customs_milestones (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, shipment_id TEXT NOT NULL REFERENCES transport_shipments(id), kind TEXT NOT NULL,
 reference TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'PENDING', occurred_at TEXT NOT NULL DEFAULT '',
 source_type TEXT NOT NULL DEFAULT 'STAFF', source_provider TEXT NOT NULL DEFAULT 'BlueHarbor staff', note TEXT NOT NULL DEFAULT '', updated TEXT NOT NULL,
 UNIQUE(shipment_id,kind)
);
CREATE TABLE IF NOT EXISTS eta_history (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, shipment_id TEXT NOT NULL REFERENCES transport_shipments(id), previous_eta TEXT NOT NULL DEFAULT '',
 revised_eta TEXT NOT NULL, reason TEXT NOT NULL, source_type TEXT NOT NULL, source_provider TEXT NOT NULL, changed_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS reefer_readings (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, shipment_id TEXT NOT NULL REFERENCES transport_shipments(id), container_id BIGINT NOT NULL REFERENCES shipment_containers(id),
 setpoint DOUBLE PRECISION, supply_temperature DOUBLE PRECISION, return_temperature DOUBLE PRECISION, humidity_percent DOUBLE PRECISION,
 alarm_code TEXT NOT NULL DEFAULT '', severity TEXT NOT NULL DEFAULT 'NORMAL', occurred_at TEXT NOT NULL,
 source_type TEXT NOT NULL CHECK(source_type IN ('STAFF','CARRIER','SENSOR')), source_provider TEXT NOT NULL, received_at TEXT NOT NULL, note TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS operational_exceptions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, shipment_id TEXT NOT NULL REFERENCES transport_shipments(id), kind TEXT NOT NULL,
 severity TEXT NOT NULL CHECK(severity IN ('INFO','WARNING','CRITICAL')), title TEXT NOT NULL, evidence TEXT NOT NULL,
 required_action TEXT NOT NULL, owner TEXT NOT NULL, due_at TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'OPEN',
 buyer_visible INTEGER NOT NULL DEFAULT 1 CHECK(buyer_visible IN (0,1)), resolution TEXT NOT NULL DEFAULT '', created TEXT NOT NULL, updated TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS notification_rules (
 event_code TEXT PRIMARY KEY, buyer_enabled INTEGER NOT NULL DEFAULT 1, staff_enabled INTEGER NOT NULL DEFAULT 1,
 severity TEXT NOT NULL DEFAULT 'INFO', message_template TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS external_event_inbox (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, provider TEXT NOT NULL, external_event_id TEXT NOT NULL,
 shipment_reference TEXT NOT NULL, payload_json TEXT NOT NULL, payload_hash TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'RECEIVED',
 error TEXT NOT NULL DEFAULT '', received_at TEXT NOT NULL, processed_at TEXT NOT NULL DEFAULT '', UNIQUE(provider,external_event_id)
);
INSERT INTO notification_rules(event_code,buyer_enabled,staff_enabled,severity,message_template) VALUES
('DEPARTED',1,1,'INFO','Shipment departed from {location}.'),('ARRIVED',1,1,'INFO','Shipment arrived at {location}.'),
('ETA_CHANGED',1,1,'WARNING','Estimated arrival changed to {eta}.'),('CUSTOMS_HOLD',1,1,'CRITICAL','Customs review requires attention.'),
('TEMPERATURE_EXCEPTION',1,1,'CRITICAL','A reefer temperature exception was recorded.') ON CONFLICT(event_code) DO NOTHING;
COMMIT;
