-- BlueHarbor Phase 3.1: vessel rotations, scheduled port calls and automatic order allocation. Run after 07.
BEGIN;
SET search_path TO blueharbor, public;

CREATE TABLE IF NOT EXISTS shipping_ports (
 code TEXT PRIMARY KEY, name TEXT NOT NULL, country TEXT NOT NULL, latitude DOUBLE PRECISION NOT NULL,
 longitude DOUBLE PRECISION NOT NULL, timezone TEXT NOT NULL DEFAULT 'UTC', active INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS shipping_carriers (
 id TEXT PRIMARY KEY, name TEXT NOT NULL, scac TEXT NOT NULL DEFAULT '', website TEXT NOT NULL DEFAULT '', active INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS shipping_vessels (
 id TEXT PRIMARY KEY, carrier_id TEXT NOT NULL REFERENCES shipping_carriers(id), name TEXT NOT NULL, imo_number TEXT NOT NULL DEFAULT '',
 flag TEXT NOT NULL DEFAULT '', image_url TEXT NOT NULL DEFAULT '', capacity_teu INTEGER NOT NULL DEFAULT 0,
 reefer_plugs INTEGER NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS service_rotations (
 id TEXT PRIMARY KEY, carrier_id TEXT NOT NULL REFERENCES shipping_carriers(id), name TEXT NOT NULL, service_code TEXT NOT NULL,
 cycle_days INTEGER NOT NULL, source_type TEXT NOT NULL DEFAULT 'SAMPLE', active INTEGER NOT NULL DEFAULT 1, updated TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS rotation_calls (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, rotation_id TEXT NOT NULL REFERENCES service_rotations(id), sequence INTEGER NOT NULL,
 port_code TEXT NOT NULL REFERENCES shipping_ports(code), day_offset INTEGER NOT NULL, terminal TEXT NOT NULL DEFAULT '',
 arrival_hour INTEGER NOT NULL DEFAULT 8, departure_hour INTEGER NOT NULL DEFAULT 20, UNIQUE(rotation_id,sequence)
);
CREATE TABLE IF NOT EXISTS vessel_sailings (
 id TEXT PRIMARY KEY, rotation_id TEXT NOT NULL REFERENCES service_rotations(id), vessel_id TEXT NOT NULL REFERENCES shipping_vessels(id),
 voyage_number TEXT NOT NULL, cycle_start TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'SCHEDULED', total_teu INTEGER NOT NULL,
 available_teu INTEGER NOT NULL, available_reefer INTEGER NOT NULL, source_type TEXT NOT NULL DEFAULT 'SAMPLE', source_provider TEXT NOT NULL DEFAULT '', updated TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS sailing_calls (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sailing_id TEXT NOT NULL REFERENCES vessel_sailings(id), sequence INTEGER NOT NULL,
 port_code TEXT NOT NULL REFERENCES shipping_ports(code), terminal TEXT NOT NULL DEFAULT '', estimated_arrival TEXT NOT NULL DEFAULT '',
 estimated_departure TEXT NOT NULL DEFAULT '', actual_arrival TEXT NOT NULL DEFAULT '', actual_departure TEXT NOT NULL DEFAULT '',
 status TEXT NOT NULL DEFAULT 'PLANNED', UNIQUE(sailing_id,sequence)
);
CREATE TABLE IF NOT EXISTS destination_port_rules (
 pattern TEXT PRIMARY KEY, port_code TEXT NOT NULL REFERENCES shipping_ports(code), priority INTEGER NOT NULL DEFAULT 100
);
ALTER TABLE transport_shipments ADD COLUMN IF NOT EXISTS sailing_id TEXT REFERENCES vessel_sailings(id);
ALTER TABLE transport_shipments ADD COLUMN IF NOT EXISTS load_call_id BIGINT REFERENCES sailing_calls(id);
ALTER TABLE transport_shipments ADD COLUMN IF NOT EXISTS discharge_call_id BIGINT REFERENCES sailing_calls(id);
ALTER TABLE transport_shipments ADD COLUMN IF NOT EXISTS allocation_source TEXT NOT NULL DEFAULT 'MANUAL';
ALTER TABLE transport_shipments ADD COLUMN IF NOT EXISTS allocated_teu INTEGER NOT NULL DEFAULT 0;

INSERT INTO shipping_ports(code,name,country,latitude,longitude,timezone) VALUES
('INCOK','Cochin Port','India',9.968,76.267,'Asia/Kolkata'),('LKCMB','Port of Colombo','Sri Lanka',6.950,79.842,'Asia/Colombo'),
('AEJEA','Jebel Ali Port','United Arab Emirates',25.011,55.061,'Asia/Dubai'),('NLRTM','Port of Rotterdam','Netherlands',51.948,4.142,'Europe/Amsterdam'),
('DEHAM','Port of Hamburg','Germany',53.537,9.980,'Europe/Berlin'),('FRLEH','Port of Le Havre','France',49.481,0.130,'Europe/Paris'),
('USNYC','Port of New York and New Jersey','United States',40.668,-74.045,'America/New_York'),('USSAV','Port of Savannah','United States',32.082,-81.090,'America/New_York'),
('SGSIN','Port of Singapore','Singapore',1.264,103.840,'Asia/Singapore'),('JPYOK','Port of Yokohama','Japan',35.454,139.638,'Asia/Tokyo'),
('USLAX','Port of Los Angeles','United States',33.738,-118.264,'America/Los_Angeles') ON CONFLICT(code) DO UPDATE SET name=excluded.name,country=excluded.country,latitude=excluded.latitude,longitude=excluded.longitude,timezone=excluded.timezone;
INSERT INTO shipping_carriers(id,name,scac,website) VALUES ('BHL-SAMPLE','BlueHarbor schedule demonstration','BHSD','') ON CONFLICT(id) DO NOTHING;
INSERT INTO shipping_vessels(id,carrier_id,name,imo_number,flag,image_url,capacity_teu,reefer_plugs) VALUES
('VSL-ATLAS','BHL-SAMPLE','MV BlueHarbor Atlas','DEMO-IMO-001','India','/vessels/blueharbor-atlas.svg',8500,900),
('VSL-PACIFIC','BHL-SAMPLE','MV BlueHarbor Pacific','DEMO-IMO-002','India','/vessels/blueharbor-pacific.svg',7200,760) ON CONFLICT(id) DO UPDATE SET name=excluded.name,image_url=excluded.image_url,capacity_teu=excluded.capacity_teu,reefer_plugs=excluded.reefer_plugs;
INSERT INTO service_rotations(id,carrier_id,name,service_code,cycle_days,source_type,updated) VALUES
('ROT-WEST','BHL-SAMPLE','India–Middle East–Europe–US rotation','BH-WEST',49,'SAMPLE',CURRENT_TIMESTAMP::TEXT),
('ROT-PACIFIC','BHL-SAMPLE','India–Asia–US Pacific rotation','BH-PAC',42,'SAMPLE',CURRENT_TIMESTAMP::TEXT) ON CONFLICT(id) DO UPDATE SET updated=excluded.updated;
INSERT INTO rotation_calls(rotation_id,sequence,port_code,day_offset,terminal,arrival_hour,departure_hour) VALUES
('ROT-WEST',1,'INCOK',0,'ICTT Vallarpadam',8,22),('ROT-WEST',2,'LKCMB',2,'Colombo International Container Terminal',7,18),
('ROT-WEST',3,'AEJEA',7,'Jebel Ali Terminal',8,20),('ROT-WEST',4,'NLRTM',20,'Maasvlakte',8,22),
('ROT-WEST',5,'DEHAM',22,'Hamburg Container Terminal',8,20),('ROT-WEST',6,'FRLEH',24,'Le Havre Terminal',8,18),
('ROT-WEST',7,'USNYC',33,'Port Newark',8,22),('ROT-WEST',8,'USSAV',36,'Garden City Terminal',8,18),
('ROT-WEST',9,'LKCMB',47,'Colombo International Container Terminal',8,18),('ROT-WEST',10,'INCOK',49,'ICTT Vallarpadam',8,20),
('ROT-PACIFIC',1,'INCOK',0,'ICTT Vallarpadam',8,22),('ROT-PACIFIC',2,'LKCMB',2,'Colombo International Container Terminal',7,18),
('ROT-PACIFIC',3,'SGSIN',7,'Pasir Panjang Terminal',8,22),('ROT-PACIFIC',4,'JPYOK',14,'Yokohama Container Terminal',8,20),
('ROT-PACIFIC',5,'USLAX',26,'Pier 400',8,22),('ROT-PACIFIC',6,'SGSIN',38,'Pasir Panjang Terminal',8,20),
('ROT-PACIFIC',7,'INCOK',42,'ICTT Vallarpadam',8,20) ON CONFLICT(rotation_id,sequence) DO UPDATE SET port_code=excluded.port_code,day_offset=excluded.day_offset,terminal=excluded.terminal,arrival_hour=excluded.arrival_hour,departure_hour=excluded.departure_hour;
INSERT INTO destination_port_rules(pattern,port_code,priority) VALUES
('jebel ali','AEJEA',1),('uae','AEJEA',10),('dubai','AEJEA',10),('rotterdam','NLRTM',1),('netherlands','NLRTM',10),
('hamburg','DEHAM',1),('germany','DEHAM',10),('le havre','FRLEH',1),('france','FRLEH',10),
('new york','USNYC',1),('new jersey','USNYC',1),('usa','USNYC',20),('united states','USNYC',20),
('savannah','USSAV',1),('singapore','SGSIN',10),('japan','JPYOK',10),('yokohama','JPYOK',1),('los angeles','USLAX',1)
ON CONFLICT(pattern) DO UPDATE SET port_code=excluded.port_code,priority=excluded.priority;

INSERT INTO destinations(name) VALUES
('New York, USA'),('Savannah, USA'),('Los Angeles, USA'),('Hamburg, Germany'),('Le Havre, France'),('Yokohama, Japan')
ON CONFLICT(name) DO NOTHING;

INSERT INTO country_rules(country,requirements,version) VALUES
('United States','["Business registration", "FDA importer or FSVP contact evidence", "Representative ID"]',1)
ON CONFLICT(country) DO NOTHING;

INSERT INTO vessel_sailings(id,rotation_id,vessel_id,voyage_number,cycle_start,status,total_teu,available_teu,available_reefer,source_type,source_provider,updated) VALUES
('SAIL-WEST-01','ROT-WEST','VSL-ATLAS','BHWA-101',(CURRENT_DATE + 3)::TEXT,'SCHEDULED',8500,180,42,'SAMPLE','BlueHarbor demonstration schedule',CURRENT_TIMESTAMP::TEXT),
('SAIL-WEST-02','ROT-WEST','VSL-ATLAS','BHWA-102',(CURRENT_DATE + 24)::TEXT,'SCHEDULED',8500,220,55,'SAMPLE','BlueHarbor demonstration schedule',CURRENT_TIMESTAMP::TEXT),
('SAIL-PAC-01','ROT-PACIFIC','VSL-PACIFIC','BHPA-201',(CURRENT_DATE + 6)::TEXT,'SCHEDULED',7200,150,36,'SAMPLE','BlueHarbor demonstration schedule',CURRENT_TIMESTAMP::TEXT),
('SAIL-PAC-02','ROT-PACIFIC','VSL-PACIFIC','BHPA-202',(CURRENT_DATE + 27)::TEXT,'SCHEDULED',7200,190,45,'SAMPLE','BlueHarbor demonstration schedule',CURRENT_TIMESTAMP::TEXT)
ON CONFLICT(id) DO UPDATE SET available_teu=excluded.available_teu,available_reefer=excluded.available_reefer,updated=excluded.updated;
INSERT INTO sailing_calls(sailing_id,sequence,port_code,terminal,estimated_arrival,estimated_departure,status)
SELECT s.id,r.sequence,r.port_code,r.terminal,
 ((s.cycle_start::date + r.day_offset) + make_interval(hours=>r.arrival_hour))::TEXT,
 ((s.cycle_start::date + r.day_offset) + make_interval(hours=>r.departure_hour))::TEXT,'PLANNED'
FROM vessel_sailings s JOIN rotation_calls r ON r.rotation_id=s.rotation_id
ON CONFLICT(sailing_id,sequence) DO UPDATE SET port_code=excluded.port_code,terminal=excluded.terminal,estimated_arrival=excluded.estimated_arrival,estimated_departure=excluded.estimated_departure;
COMMIT;
