-- PostgreSQL Authoritative Schema
CREATE TABLE users (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email TEXT UNIQUE NOT NULL, auth_uid TEXT,
 name TEXT NOT NULL, company TEXT NOT NULL DEFAULT '', country TEXT NOT NULL DEFAULT 'UAE',
 registration TEXT NOT NULL DEFAULT '', address TEXT NOT NULL DEFAULT '', phone TEXT NOT NULL DEFAULT '',
 verified TEXT NOT NULL DEFAULT 'DRAFT', created TEXT NOT NULL
);
CREATE TABLE sessions (token TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), expires INTEGER NOT NULL);
CREATE TABLE products (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, category TEXT NOT NULL, grade TEXT NOT NULL,
 origin TEXT NOT NULL, cents_per_kg INTEGER NOT NULL CHECK(cents_per_kg>0),
 minimum_kg INTEGER NOT NULL, description TEXT NOT NULL
);
CREATE TABLE lots (
 id TEXT PRIMARY KEY, product_id INTEGER NOT NULL REFERENCES products(id),
 available_kg INTEGER NOT NULL CHECK(available_kg>=0), reserved_kg INTEGER NOT NULL DEFAULT 0 CHECK(reserved_kg>=0),
 expiry TEXT NOT NULL
);
CREATE TABLE orders (
 id TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), product_id INTEGER NOT NULL REFERENCES products(id),
 product_name TEXT NOT NULL, kg INTEGER NOT NULL, cents_per_kg INTEGER NOT NULL,
 shipping INTEGER NOT NULL, total INTEGER NOT NULL, destination TEXT NOT NULL, service TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'CONFIRMED', created TEXT NOT NULL, request_key TEXT NOT NULL, fingerprint TEXT NOT NULL,
 UNIQUE(user_id,request_key)
);
CREATE TABLE allocations (order_id TEXT REFERENCES orders(id),lot_id TEXT REFERENCES lots(id),kg INTEGER NOT NULL);
CREATE TABLE events (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,order_id TEXT REFERENCES orders(id),title TEXT NOT NULL,note TEXT NOT NULL,created TEXT NOT NULL);
CREATE TABLE documents (
 id TEXT PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id),kind TEXT NOT NULL,name TEXT NOT NULL,
 mime TEXT NOT NULL,content TEXT NOT NULL,content_size INTEGER NOT NULL DEFAULT 0,expiry TEXT NOT NULL,created TEXT NOT NULL
);
CREATE TABLE notifications (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id INTEGER REFERENCES users(id),message TEXT NOT NULL,seen INTEGER NOT NULL DEFAULT 0,created TEXT NOT NULL);
CREATE TABLE audit (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id INTEGER,action TEXT NOT NULL,detail TEXT NOT NULL,created TEXT NOT NULL);
CREATE TABLE login_attempts (identity TEXT PRIMARY KEY,count INTEGER NOT NULL,started INTEGER NOT NULL);
CREATE TABLE demo_accounts (user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY REFERENCES users(id));
CREATE TABLE tanks (id TEXT PRIMARY KEY,lot_id TEXT UNIQUE NOT NULL REFERENCES lots(id),zone TEXT NOT NULL);
CREATE TABLE product_sources (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY REFERENCES products(id),
    region TEXT NOT NULL,
    export_port TEXT NOT NULL,
    facility TEXT NOT NULL
);
CREATE TABLE staff (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email TEXT NOT NULL UNIQUE, auth_uid TEXT,
 name TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('ADMIN','VERIFIER','OPERATIONS')),
 active INTEGER NOT NULL DEFAULT 1, created TEXT NOT NULL
);
CREATE TABLE staff_sessions (token TEXT PRIMARY KEY,staff_id INTEGER NOT NULL REFERENCES staff(id),expires INTEGER NOT NULL);
CREATE TABLE settings (key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE country_rules (country TEXT PRIMARY KEY,requirements TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE shipping_services (name TEXT PRIMARY KEY,cents INTEGER NOT NULL CHECK(cents>=0));
CREATE TABLE destinations (name TEXT PRIMARY KEY);
CREATE TABLE product_admin (product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY REFERENCES products(id),published INTEGER NOT NULL DEFAULT 1,image TEXT NOT NULL DEFAULT '',reorder_kg INTEGER NOT NULL DEFAULT 1000,scientific_name TEXT NOT NULL DEFAULT '');
CREATE TABLE product_images (id TEXT PRIMARY KEY,name TEXT NOT NULL,mime TEXT NOT NULL,content TEXT NOT NULL,content_size INTEGER NOT NULL DEFAULT 0);
CREATE TABLE warehouses (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE,location TEXT NOT NULL,kind TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE lot_admin (lot_id TEXT PRIMARY KEY REFERENCES lots(id),warehouse_id INTEGER REFERENCES warehouses(id),quality TEXT NOT NULL DEFAULT 'RELEASED',production_date TEXT NOT NULL DEFAULT '',note TEXT NOT NULL DEFAULT '');
CREATE TABLE tank_admin (tank_id TEXT PRIMARY KEY REFERENCES tanks(id),capacity_kg INTEGER NOT NULL DEFAULT 10000,status TEXT NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE condition_readings (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tank_id TEXT NOT NULL REFERENCES tanks(id),temperature REAL,oxygen REAL,note TEXT NOT NULL,created TEXT NOT NULL,staff_id INTEGER REFERENCES staff(id));
CREATE TABLE stock_movements (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,lot_id TEXT NOT NULL REFERENCES lots(id),kind TEXT NOT NULL,available_delta INTEGER NOT NULL,reserved_delta INTEGER NOT NULL,reason TEXT NOT NULL,staff_id INTEGER REFERENCES staff(id),order_id TEXT,created TEXT NOT NULL);
CREATE TABLE verification_cases (user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY REFERENCES users(id),revision INTEGER NOT NULL DEFAULT 1,assignee INTEGER REFERENCES staff(id),submitted TEXT,note TEXT NOT NULL DEFAULT '',decision_by INTEGER REFERENCES staff(id),decided TEXT);
CREATE TABLE document_reviews (document_id TEXT PRIMARY KEY REFERENCES documents(id),status TEXT NOT NULL DEFAULT 'PENDING',note TEXT NOT NULL DEFAULT '',reviewer INTEGER REFERENCES staff(id));
CREATE TABLE ai_jobs (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,kind TEXT NOT NULL,entity_id TEXT NOT NULL,revision TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'QUEUED',attempts INTEGER NOT NULL DEFAULT 0,model TEXT NOT NULL DEFAULT '',input_json TEXT NOT NULL DEFAULT '{}',output_json TEXT NOT NULL DEFAULT '{}',error TEXT NOT NULL DEFAULT '',created TEXT NOT NULL,updated TEXT NOT NULL);
CREATE TABLE alerts (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,alert_key TEXT NOT NULL UNIQUE,kind TEXT NOT NULL,severity TEXT NOT NULL,title TEXT NOT NULL,evidence TEXT NOT NULL,recommendation TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'OPEN',assignee INTEGER REFERENCES staff(id),resolution TEXT NOT NULL DEFAULT '',created TEXT NOT NULL,updated TEXT NOT NULL);
CREATE TABLE shipments (order_id TEXT PRIMARY KEY REFERENCES orders(id),origin_port TEXT NOT NULL DEFAULT '',carrier TEXT NOT NULL DEFAULT '',container TEXT NOT NULL DEFAULT '',vessel TEXT NOT NULL DEFAULT '',departure TEXT NOT NULL DEFAULT '',eta TEXT NOT NULL DEFAULT '',arrival TEXT NOT NULL DEFAULT '',location TEXT NOT NULL DEFAULT '');
CREATE TABLE order_operations (order_id TEXT PRIMARY KEY REFERENCES orders(id),on_hold INTEGER NOT NULL DEFAULT 0,internal_note TEXT NOT NULL DEFAULT '');
CREATE TABLE trade_documents (id TEXT PRIMARY KEY,order_id TEXT NOT NULL REFERENCES orders(id),kind TEXT NOT NULL,name TEXT NOT NULL,mime TEXT NOT NULL,content TEXT NOT NULL,content_size INTEGER NOT NULL DEFAULT 0,published INTEGER NOT NULL DEFAULT 0,version INTEGER NOT NULL DEFAULT 1,status TEXT NOT NULL DEFAULT 'DRAFT',issuer TEXT NOT NULL DEFAULT '',document_number TEXT NOT NULL DEFAULT '',issue_date TEXT NOT NULL DEFAULT '',expiry_date TEXT NOT NULL DEFAULT '',created TEXT NOT NULL,staff_id INTEGER REFERENCES staff(id));
CREATE TABLE admin_audit (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,staff_id INTEGER REFERENCES staff(id),action TEXT NOT NULL,entity TEXT NOT NULL,reason TEXT NOT NULL,before_json TEXT NOT NULL,after_json TEXT NOT NULL,created TEXT NOT NULL);
CREATE TABLE changes (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,topic TEXT NOT NULL,user_id INTEGER,created TEXT NOT NULL);
CREATE TABLE email_outbox (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id INTEGER REFERENCES users(id),subject TEXT NOT NULL,body TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'NOT_CONNECTED',attempts INTEGER NOT NULL DEFAULT 0,error TEXT NOT NULL DEFAULT '',created TEXT NOT NULL,updated TEXT NOT NULL);

CREATE TABLE compliance_rule_sets(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country TEXT NOT NULL,
    product_category TEXT NOT NULL,
    requirement_code TEXT NOT NULL,
    document_name TEXT NOT NULL,
    issuer TEXT NOT NULL,
    buyer_owned INTEGER NOT NULL,
    blocking INTEGER NOT NULL,
    lead_days INTEGER NOT NULL,
    source_url TEXT NOT NULL,
    reviewed_on TEXT NOT NULL,
    active INTEGER NOT NULL,
    required_stage TEXT NOT NULL,
    responsible_party TEXT NOT NULL,
    evidence_type TEXT NOT NULL,
    original_required INTEGER NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    updated TEXT NOT NULL
);

CREATE TABLE order_document_requirements(
    order_id TEXT NOT NULL REFERENCES orders(id),
    requirement_code TEXT NOT NULL,
    document_name TEXT NOT NULL,
    owner TEXT NOT NULL,
    blocking INTEGER NOT NULL,
    status TEXT NOT NULL,
    source_rule_id INTEGER REFERENCES compliance_rule_sets(id),
    note TEXT NOT NULL,
    updated TEXT NOT NULL,
    required_stage TEXT NOT NULL,
    responsible_party TEXT NOT NULL,
    official_issuer TEXT NOT NULL,
    evidence_type TEXT NOT NULL,
    original_required INTEGER NOT NULL,
    UNIQUE(order_id, requirement_code)
);

CREATE TABLE exporter_credentials(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    authority TEXT NOT NULL,
    number TEXT NOT NULL,
    scope TEXT NOT NULL,
    issued TEXT NOT NULL,
    expires TEXT NOT NULL,
    status TEXT NOT NULL,
    notes TEXT NOT NULL,
    updated TEXT NOT NULL
);

CREATE TABLE lot_arrivals(
    lot_id TEXT PRIMARY KEY REFERENCES lots(id),
    received_date TEXT NOT NULL
);

CREATE TABLE shipping_carriers(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    scac TEXT,
    active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE shipping_vessels(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrier_id INTEGER REFERENCES shipping_carriers(id),
    name TEXT NOT NULL,
    imo_number TEXT,
    flag TEXT,
    image_url TEXT,
    capacity_teu INTEGER,
    reefer_plugs INTEGER,
    active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE service_rotations(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrier_id INTEGER REFERENCES shipping_carriers(id),
    name TEXT NOT NULL,
    service_code TEXT,
    cycle_days INTEGER,
    active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE vessel_sailings(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vessel_id INTEGER REFERENCES shipping_vessels(id),
    rotation_id INTEGER REFERENCES service_rotations(id),
    voyage_number TEXT NOT NULL,
    status TEXT NOT NULL,
    cycle_start TEXT,
    available_teu REAL,
    available_reefer REAL,
    updated TEXT NOT NULL
);

CREATE TABLE shipping_ports(
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    country TEXT,
    latitude REAL,
    longitude REAL,
    timezone TEXT
);

CREATE TABLE sailing_calls(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sailing_id INTEGER REFERENCES vessel_sailings(id),
    port_code TEXT REFERENCES shipping_ports(code),
    sequence INTEGER NOT NULL,
    eta TEXT,
    etd TEXT,
    status TEXT,
    actual_arrival TEXT,
    actual_departure TEXT
);

CREATE TABLE destination_port_rules(
    port_code TEXT PRIMARY KEY REFERENCES shipping_ports(code),
    pattern TEXT NOT NULL,
    priority INTEGER NOT NULL,
    rules_json TEXT NOT NULL
);

CREATE TABLE transport_shipments(
    id TEXT PRIMARY KEY,
    booking_reference TEXT,
    mode TEXT,
    carrier TEXT,
    vessel TEXT,
    voyage TEXT,
    status TEXT,
    origin_port TEXT,
    destination_port TEXT,
    origin_lat REAL,
    origin_lon REAL,
    destination_lat REAL,
    destination_lon REAL,
    planned_departure TEXT,
    planned_arrival TEXT,
    actual_departure TEXT,
    actual_arrival TEXT,
    booking_cutoff TEXT,
    documentation_cutoff TEXT,
    vgm_cutoff TEXT,
    shipping_instructions TEXT,
    sailing_id INTEGER REFERENCES vessel_sailings(id),
    load_call_id INTEGER REFERENCES sailing_calls(id),
    discharge_call_id INTEGER REFERENCES sailing_calls(id),
    allocation_source TEXT,
    allocated_teu REAL,
    created TEXT NOT NULL,
    updated TEXT NOT NULL
);

CREATE TABLE shipment_orders(
    shipment_id TEXT REFERENCES transport_shipments(id),
    order_id TEXT REFERENCES orders(id),
    created TEXT NOT NULL,
    PRIMARY KEY(shipment_id, order_id),
    UNIQUE(order_id)
);

CREATE TABLE transport_legs(
    shipment_id TEXT REFERENCES transport_shipments(id),
    sequence INTEGER NOT NULL,
    mode TEXT,
    carrier TEXT,
    vessel TEXT,
    voyage TEXT,
    origin_name TEXT,
    origin_lat REAL,
    origin_lon REAL,
    destination_name TEXT,
    destination_lat REAL,
    destination_lon REAL,
    planned_departure TEXT,
    planned_arrival TEXT,
    status TEXT,
    PRIMARY KEY(shipment_id, sequence)
);

CREATE TABLE shipment_containers(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id TEXT REFERENCES transport_shipments(id),
    container_number TEXT NOT NULL UNIQUE,
    container_type TEXT,
    seal_number TEXT,
    stuffing_status TEXT,
    stuffed_at TEXT,
    reefer_setpoint REAL,
    ventilation_cbm REAL,
    humidity_percent REAL,
    tare_kg REAL,
    verified_gross_kg REAL,
    vgm_method TEXT,
    vgm_party TEXT,
    vgm_reference TEXT,
    vgm_at TEXT,
    updated TEXT NOT NULL
);

CREATE TABLE carrier_events(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id TEXT REFERENCES transport_shipments(id),
    event_code TEXT NOT NULL,
    event_label TEXT NOT NULL,
    event_type TEXT NOT NULL,
    occurred_at TEXT,
    location_name TEXT,
    latitude REAL,
    longitude REAL,
    source_type TEXT NOT NULL,
    source_provider TEXT NOT NULL,
    received_at TEXT NOT NULL,
    note TEXT NOT NULL
);

CREATE TABLE customs_milestones(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id TEXT REFERENCES transport_shipments(id),
    kind TEXT NOT NULL,
    reference TEXT,
    status TEXT NOT NULL,
    occurred_at TEXT,
    source_type TEXT NOT NULL,
    source_provider TEXT NOT NULL,
    note TEXT NOT NULL,
    updated TEXT NOT NULL,
    UNIQUE(shipment_id, kind)
);

CREATE TABLE operational_exceptions(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id TEXT REFERENCES transport_shipments(id),
    kind TEXT NOT NULL,
    severity TEXT NOT NULL,
    title TEXT NOT NULL,
    evidence TEXT NOT NULL,
    required_action TEXT NOT NULL,
    owner TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'OPEN',
    resolution TEXT,
    due_at TEXT,
    buyer_visible INTEGER NOT NULL DEFAULT 0,
    created TEXT NOT NULL,
    updated TEXT NOT NULL
);

CREATE TABLE reefer_readings(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id TEXT REFERENCES transport_shipments(id),
    container_id INTEGER REFERENCES shipment_containers(id),
    setpoint REAL,
    supply_temperature REAL,
    return_temperature REAL,
    humidity_percent REAL,
    alarm_code TEXT,
    severity TEXT,
    occurred_at TEXT,
    source_type TEXT NOT NULL,
    source_provider TEXT NOT NULL,
    received_at TEXT NOT NULL,
    note TEXT NOT NULL
);

CREATE TABLE eta_history(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id TEXT REFERENCES transport_shipments(id),
    previous_eta TEXT,
    revised_eta TEXT,
    reason TEXT NOT NULL,
    source_type TEXT NOT NULL,
    source_provider TEXT NOT NULL,
    changed_at TEXT NOT NULL
);

CREATE TABLE discount_proposals(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER REFERENCES products(id),
    lot_id TEXT REFERENCES lots(id),
    percent REAL NOT NULL,
    ends_on TEXT NOT NULL,
    reason TEXT NOT NULL,
    created TEXT NOT NULL,
    proposed_by INTEGER REFERENCES staff(id),
    base_cents INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'PROPOSED',
    decided TEXT,
    decided_by INTEGER REFERENCES staff(id),
    decision_note TEXT
);

CREATE INDEX idx_trade_documents_order ON trade_documents(order_id);
CREATE INDEX idx_shipment_containers_shipment ON shipment_containers(shipment_id);
CREATE INDEX idx_carrier_events_shipment ON carrier_events(shipment_id);
CREATE INDEX idx_operational_exceptions_shipment ON operational_exceptions(shipment_id);
CREATE INDEX idx_reefer_readings_shipment ON reefer_readings(shipment_id);
