CREATE TABLE IF NOT EXISTS staff (
 id INTEGER PRIMARY KEY, email TEXT NOT NULL UNIQUE, password TEXT NOT NULL,
 name TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('ADMIN','VERIFIER','OPERATIONS')),
 active INTEGER NOT NULL DEFAULT 1, created TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS staff_sessions(token TEXT PRIMARY KEY,staff_id INTEGER NOT NULL REFERENCES staff(id),expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS country_rules(country TEXT PRIMARY KEY,requirements TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS shipping_services(name TEXT PRIMARY KEY,cents INTEGER NOT NULL CHECK(cents>=0));
CREATE TABLE IF NOT EXISTS destinations(name TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS product_admin(product_id INTEGER PRIMARY KEY REFERENCES products(id),published INTEGER NOT NULL DEFAULT 1,image TEXT NOT NULL DEFAULT '',reorder_kg INTEGER NOT NULL DEFAULT 1000,scientific_name TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS product_images(id TEXT PRIMARY KEY,name TEXT NOT NULL,mime TEXT NOT NULL,content BYTEA NOT NULL);
CREATE TABLE IF NOT EXISTS warehouses(id INTEGER PRIMARY KEY,name TEXT NOT NULL UNIQUE,location TEXT NOT NULL,kind TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS lot_admin(lot_id TEXT PRIMARY KEY REFERENCES lots(id),warehouse_id INTEGER REFERENCES warehouses(id),quality TEXT NOT NULL DEFAULT 'RELEASED',production_date TEXT NOT NULL DEFAULT '',note TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS tank_admin(tank_id TEXT PRIMARY KEY REFERENCES tanks(id),capacity_kg INTEGER NOT NULL DEFAULT 10000,status TEXT NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE IF NOT EXISTS condition_readings(id INTEGER PRIMARY KEY,tank_id TEXT NOT NULL REFERENCES tanks(id),temperature REAL,oxygen REAL,note TEXT NOT NULL,created TEXT NOT NULL,staff_id INTEGER REFERENCES staff(id));
CREATE TABLE IF NOT EXISTS stock_movements(id INTEGER PRIMARY KEY,lot_id TEXT NOT NULL REFERENCES lots(id),kind TEXT NOT NULL,available_delta INTEGER NOT NULL,reserved_delta INTEGER NOT NULL,reason TEXT NOT NULL,staff_id INTEGER REFERENCES staff(id),order_id TEXT,created TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_movements_lot ON stock_movements(lot_id,id);
CREATE TABLE IF NOT EXISTS verification_cases(user_id INTEGER PRIMARY KEY REFERENCES users(id),revision INTEGER NOT NULL DEFAULT 1,assignee INTEGER REFERENCES staff(id),submitted TEXT,note TEXT NOT NULL DEFAULT '',decision_by INTEGER REFERENCES staff(id),decided TEXT);
CREATE TABLE IF NOT EXISTS document_reviews(document_id TEXT PRIMARY KEY REFERENCES documents(id),status TEXT NOT NULL DEFAULT 'PENDING',note TEXT NOT NULL DEFAULT '',reviewer INTEGER REFERENCES staff(id));
CREATE TABLE IF NOT EXISTS ai_jobs(id INTEGER PRIMARY KEY,kind TEXT NOT NULL,entity_id TEXT NOT NULL,revision TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'QUEUED',attempts INTEGER NOT NULL DEFAULT 0,model TEXT NOT NULL DEFAULT '',input_json TEXT NOT NULL DEFAULT '{}',output_json TEXT NOT NULL DEFAULT '{}',error TEXT NOT NULL DEFAULT '',created TEXT NOT NULL,updated TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_ai_status ON ai_jobs(status,id);
CREATE TABLE IF NOT EXISTS alerts(id INTEGER PRIMARY KEY,alert_key TEXT NOT NULL UNIQUE,kind TEXT NOT NULL,severity TEXT NOT NULL,title TEXT NOT NULL,evidence TEXT NOT NULL,recommendation TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'OPEN',assignee INTEGER REFERENCES staff(id),resolution TEXT NOT NULL DEFAULT '',created TEXT NOT NULL,updated TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS shipments(order_id TEXT PRIMARY KEY REFERENCES orders(id),origin_port TEXT NOT NULL DEFAULT '',carrier TEXT NOT NULL DEFAULT '',container TEXT NOT NULL DEFAULT '',vessel TEXT NOT NULL DEFAULT '',departure TEXT NOT NULL DEFAULT '',eta TEXT NOT NULL DEFAULT '',arrival TEXT NOT NULL DEFAULT '',location TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS order_operations(order_id TEXT PRIMARY KEY REFERENCES orders(id),on_hold INTEGER NOT NULL DEFAULT 0,internal_note TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS trade_documents(id TEXT PRIMARY KEY,order_id TEXT NOT NULL REFERENCES orders(id),kind TEXT NOT NULL,name TEXT NOT NULL,mime TEXT NOT NULL,content BYTEA NOT NULL,published INTEGER NOT NULL DEFAULT 0,version INTEGER NOT NULL DEFAULT 1,created TEXT NOT NULL,staff_id INTEGER REFERENCES staff(id));
CREATE INDEX IF NOT EXISTS idx_trade_order ON trade_documents(order_id,created);
CREATE TABLE IF NOT EXISTS admin_audit(id INTEGER PRIMARY KEY,staff_id INTEGER REFERENCES staff(id),action TEXT NOT NULL,entity TEXT NOT NULL,reason TEXT NOT NULL,before_json TEXT NOT NULL,after_json TEXT NOT NULL,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS changes(id INTEGER PRIMARY KEY,topic TEXT NOT NULL,user_id INTEGER,created TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_changes_topic_user ON changes(topic,user_id,id);
CREATE TABLE IF NOT EXISTS email_outbox(id INTEGER PRIMARY KEY,user_id INTEGER REFERENCES users(id),subject TEXT NOT NULL,body TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'NOT_CONNECTED',attempts INTEGER NOT NULL DEFAULT 0,error TEXT NOT NULL DEFAULT '',created TEXT NOT NULL,updated TEXT NOT NULL);
