'use client';
import { ArrowUpRight, FileCheck2, Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';

// Server snapshot rows are heterogeneous by design in this operational console.
// oxlint-disable-next-line typescript/no-explicit-any
type Row=Record<string,any>;
type Field={key:string;label:string;type?:string;options?:[string|number,string][];optional?:boolean};
type Props={state:Row;filtered:(rows:Row[])=>Row[];edit:(title:string,path:string,data:Row,fields:Field[])=>void};
const states=['DRAFT','UNDER_REVIEW','CORRECTION_REQUIRED','ISSUED','RELEASED','SUPERSEDED'];
const reqStates=['WAITING','SUBMITTED','UNDER_REVIEW','CORRECTION_REQUIRED','ISSUED','RELEASED','NOT_REQUIRED'];
const choice=(values:string[])=>values.map(x=>[x,x.replaceAll('_',' ')] as [string,string]);
export default function DocumentationConsole({state:s,filtered,edit}:Props){
 const orderOptions=s.orders.map((o:Row)=>[o.id,`${o.id} · ${o.product_name}`] as [string,string]);
 return <div className="compliance-console">
  <section className="admin-hero compliance-hero"><div><p className="admin-eyebrow">PHASE 2 · DOCUMENT CONTROL</p><h1>Clear every order with evidence.</h1><p>Destination rules create the checklist. Staff issue, review and release every record with an official source and audit trail.</p></div><div className="trade-kpis"><span><b>{s.compliance.requirements.filter((r:Row)=>r.blocking).length}</b><small>Orders blocked</small></span><span><b>{s.compliance.credentials.filter((c:Row)=>c.status!=='ACTIVE').length}</b><small>Credentials due</small></span></div></section>
  <section className="admin-panel"><div className="admin-panel-heading"><div><h2>Order readiness</h2><p className="admin-muted">Open any requirement to record evidence, correction, issue or release status.</p></div></div>
   <div className="readiness-grid">{filtered(s.compliance.requirements).map((r:Row)=><article className="readiness-card" key={r.order_id}><header><div><small>{r.order_id} · {r.country}</small><h3>{r.product_name}</h3></div><b>{r.started}/{r.total} started</b></header><div className="readiness-bar"><span style={{width:`${r.progress||0}%`}}/></div><p>{r.released} released · {r.blocking ? `${r.blocking} blocking items remain` : 'Documentation gate clear'}</p><div className="requirement-actions">{r.items.map((item:Row)=><Button key={item.requirement_code} size="sm" variant="outline" onClick={()=>item.document?edit('Review '+item.document_name,'document-status',{id:item.document.id,status:item.document.status,issuer:item.document.issuer,document_number:item.document.document_number,issue_date:item.document.issue_date,expiry_date:item.document.expiry_date,note:''},[{key:'status',label:'Document status',options:choice(states)},{key:'issuer',label:'Issuer',optional:true},{key:'document_number',label:'Document number / reference',optional:true},{key:'issue_date',label:'Issue date',type:'date',optional:true},{key:'expiry_date',label:'Expiry date',type:'date',optional:true},{key:'note',label:'Review note',type:'textarea',optional:true}]):item.owner==='EXPORTER'?edit('Attach '+item.document_name,'trade-document',{order_id:r.order_id,kind:item.document_name},[{key:'order_id',label:'Order',options:orderOptions},{key:'kind',label:'Document type'},{key:'file',label:'Soft copy (PDF, PNG or JPEG · max 5 MB)',type:'file'}]):edit(item.document_name,'document-requirement',{order_id:r.order_id,requirement_code:item.requirement_code,status:item.status,note:item.note||''},[{key:'status',label:'Buyer evidence state',options:choice(reqStates)},{key:'note',label:'Reference / evidence note',type:'textarea'}])}>{item.document_name}<small>{item.document?'Review attachment':item.owner==='EXPORTER'?'Attach soft copy':'Record buyer evidence'} · {item.status.replaceAll('_',' ')}</small></Button>)}</div></article>)}</div>
  </section>
  <section className="admin-panel"><div className="admin-panel-heading"><div><h2>Controlled document library</h2><p className="admin-muted">Released documents become buyer-visible and enter the clearance pack.</p></div><div className="admin-row-actions"><Button variant="outline" onClick={()=>edit('Upload document','trade-document',{order_id:s.orders[0]?.id},[{key:'order_id',label:'Order',options:orderOptions},{key:'kind',label:'Requirement / document name'},{key:'file',label:'PDF, PNG or JPEG · max 5 MB',type:'file'}])}><Plus size={15}/>Upload</Button><Button onClick={()=>edit('Generate document','generate-document',{order_id:s.orders[0]?.id,kind:'Informational invoice'},[{key:'order_id',label:'Order',options:orderOptions},{key:'kind',label:'Template',options:choice(['Order confirmation','Informational invoice','Packing list'])}])}><FileCheck2 size={15}/>Generate</Button></div></div>
   <div className="document-control-list">{filtered(s.documents).map((d:Row)=><article key={d.id}><div><small>{d.order_id} · version {d.version}</small><h3>{d.kind}</h3><p>{d.name}</p></div><div><span className={'admin-pill pill-'+d.status.toLowerCase().replaceAll('_','-')}>{d.status.replaceAll('_',' ')}</span><small>{d.issuer||'Issuer pending'}{d.document_number?' · '+d.document_number:''}</small></div><div className="admin-row-actions"><a className="admin-link" href={'/api/admin/trade-document/'+d.id}>Download</a><Button size="sm" onClick={()=>edit('Review '+d.kind,'document-status',{id:d.id,status:d.status,issuer:d.issuer,document_number:d.document_number,issue_date:d.issue_date,expiry_date:d.expiry_date,note:''},[{key:'status',label:'Document status',options:choice(states)},{key:'issuer',label:'Issuer',optional:true},{key:'document_number',label:'Document number / reference',optional:true},{key:'issue_date',label:'Issue date',type:'date',optional:true},{key:'expiry_date',label:'Expiry date',type:'date',optional:true},{key:'note',label:'Review note',type:'textarea',optional:true}])}>Review</Button></div></article>)}</div>
  </section>
  <section className="admin-panel"><div className="admin-panel-heading"><div><h2>Exporter credential register</h2><p className="admin-muted">Track registration scope and renewal dates before dispatch is affected.</p></div><Button onClick={()=>edit('Add exporter credential','exporter-credential',{status:'ACTIVE'},[{key:'name',label:'Credential name'},{key:'authority',label:'Issuing authority'},{key:'number',label:'Registration / certificate number'},{key:'scope',label:'Approved scope',type:'textarea'},{key:'issued',label:'Issued date',type:'date',optional:true},{key:'expires',label:'Expiry date',type:'date'},{key:'status',label:'Status',options:choice(['ACTIVE','RENEWAL_DUE','EXPIRED','SUSPENDED'])},{key:'notes',label:'Notes',type:'textarea',optional:true}])}><Plus size={15}/>Add credential</Button></div><div className="credential-grid">{s.compliance.credentials.map((c:Row)=><article key={c.id}><span className={'admin-pill pill-'+c.status.toLowerCase()}>{c.status.replaceAll('_',' ')}</span><h3>{c.name}</h3><p>{c.authority} · {c.number}</p><small>Expires {c.expires} · {c.scope}</small></article>)}</div></section>
  <section className="admin-panel"><div className="admin-panel-heading"><div><h2>Destination rule packs</h2><p className="admin-muted">Sources are dated. Have an export professional or customs broker validate rules before production use.</p></div><Button onClick={()=>edit('Add compliance requirement','compliance-rule',{country:'*',product_category:'*',buyer_owned:0,blocking:1,lead_days:2,reviewed_on:new Date().toISOString().slice(0,10),active:1,required_stage:'PRE_LOADING',responsible_party:'EXPORTER',evidence_type:'DOCUMENT',original_required:0},[{key:'country',label:'Destination country (* for all)'},{key:'product_category',label:'Product category (* for all)'},{key:'requirement_code',label:'Stable requirement code'},{key:'document_name',label:'Document / evidence name'},{key:'required_stage',label:'Required stage',options:choice(['PRE_CUSTOMS','PRE_LOADING','POST_DEPARTURE','PRE_ARRIVAL','DESTINATION_RELEASE'])},{key:'responsible_party',label:'Responsible party',options:choice(['EXPORTER','CUSTOMS_BROKER','APPROVED_ESTABLISHMENT','COMPETENT_AUTHORITY','CARRIER','BUYER_IMPORTER'])},{key:'issuer',label:'Official issuer'},{key:'evidence_type',label:'Evidence type',options:choice(['DOCUMENT','REFERENCE'])},{key:'original_required',label:'Original required',options:[[0,'No'],[1,'Yes']]},{key:'buyer_owned',label:'Buyer-owned task',options:[[0,'No'],[1,'Yes']]},{key:'blocking',label:'Blocks its gate',options:[[1,'Yes'],[0,'No']]},{key:'lead_days',label:'Lead time (days)',type:'number'},{key:'source_url',label:'Official source URL'},{key:'reviewed_on',label:'Last reviewed',type:'date'},{key:'active',label:'Rule state',options:[[1,'Active'],[0,'Inactive']]}])}><Plus size={15}/>Add rule</Button></div><div className="rule-table">{s.compliance.rules.map((r:Row)=><article key={r.id}><div><small>{r.country} · {r.product_category} · v{r.version}</small><h3>{r.document_name}</h3><p>{r.required_stage.replaceAll('_',' ')} · {r.responsible_party.replaceAll('_',' ')} · issued by {r.issuer}</p></div><a className="admin-link" href={r.source_url} target="_blank" rel="noreferrer">Official source <ArrowUpRight size={14}/></a></article>)}</div></section>
 </div>
}
