'use client';
import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Bot, ExternalLink, FileSearch, MessageSquareText, Search, ShieldCheck, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { NativeSelect } from '@/components/ui/native-select';
import { Textarea } from '@/components/ui/textarea';

type Row=Record<string,any>;
type Catalog={documents:Row[];orders:Row[];buyers:Row[];shipments:Row[]};
async function aiApi(path:string,data?:unknown){
 const res=await fetch('/api/admin/'+path,{credentials:'same-origin',...(data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-BlueHarbor':'1'},body:JSON.stringify(data)})});
 const value=await res.json() as Row;
 if(!res.ok) throw new Error(value.error||'Request failed');
 return value;
}
const pretty=(value:unknown)=>JSON.stringify(value,null,2);
function Sources({sources=[]}:{sources?:Row[]}){if(!sources.length)return null;return <div className="gemini-sources"><b>Source citations</b>{sources.map((s)=><a key={s.citation+s.id} href={s.href} target="_blank" rel="noreferrer"><span>{s.citation}</span>{s.label}<ExternalLink size={13}/></a>)}</div>}
function Result({value}:{value:Row|null}){if(!value)return null;const result=value.result||{};return <div className="gemini-result"><div className="gemini-result-head"><b>Gemini proposal</b><span>Human review required</span></div>{result.subject&&<h3>{result.subject}</h3>}{result.body&&<div className="gemini-draft">{result.body}</div>}{result.summary&&<p className="gemini-summary">{result.summary}</p>}{result.executive_summary&&<p className="gemini-summary">{result.executive_summary}</p>}{result.answer&&<p className="gemini-summary">{result.answer}</p>}{result.fields&&<div className="gemini-fields">{Object.entries(result.fields).map(([k,v])=><div key={k}><span>{k.replaceAll('_',' ')}</span><b>{typeof v==='object'?pretty(v):String(v)}</b></div>)}</div>}<details><summary>Structured analysis</summary><pre>{pretty(result)}</pre></details><Sources sources={value.sources}/></div>}
export default function GeminiAssistant({state}:{state:Row}){
 const [status,setStatus]=useState<Row|null>(null),[catalog,setCatalog]=useState<Catalog>({documents:[],orders:[],buyers:[],shipments:[]}),[error,setError]=useState(''),[busy,setBusy]=useState(''),[result,setResult]=useState<Row|null>(null);
 const [doc,setDoc]=useState(''),[order,setOrder]=useState(''),[search,setSearch]=useState(''),[draftKind,setDraftKind]=useState('BUYER_MESSAGE'),[instructions,setInstructions]=useState('');
 useEffect(()=>{void Promise.all([aiApi('ai-status'),aiApi('ai-catalog')]).then(([s,c])=>{setStatus(s);setCatalog(c as Catalog);setOrder((c as Catalog).orders?.[0]?.id||'');const first=(c as Catalog).documents?.find((d:Row)=>d.scope==='trade'||d.ai_allowed!==false);if(first)setDoc(first.scope+'|'+first.id)}).catch(e=>setError((e as Error).message))},[]);
 const selectedDoc=useMemo(()=>catalog.documents.find(d=>doc===d.scope+'|'+d.id),[catalog,doc]);
 async function run(name:string,path:string,data:Row){setBusy(name);setError('');setResult(null);try{setResult(await aiApi(path,data))}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 return <div className="gemini-console">
  <section className="admin-hero gemini-hero"><div><p className="admin-eyebrow">PHASE 5 · GEMINI ASSISTANCE</p><h1>Analyse records. Keep decisions human.</h1><p>Gemini can extract, compare, search, summarize and draft. It cannot apply operational approvals or state changes.</p></div><div className="gemini-health"><Sparkles size={24}/><div><b>{status?.configured?'Gemini connected':'Gemini not configured'}</b><small>{status?.model||'Backend status loading…'}</small></div></div></section>
  <section className="gemini-guardrail"><ShieldCheck size={20}/><div><b>Human-control boundary</b><p>Buyer verification, quality release, customs clearance, inventory changes and financial approvals remain in the existing staff workflows.</p></div></section>
  {!status?.configured&&<section className="admin-panel gemini-setup"><AlertTriangle size={20}/><div><b>Configuration required</b><p>Add <code>GEMINI_API_KEY</code> to the backend environment. Buyer-submitted document processing is disabled by default and sensitive identity documents are always blocked.</p></div></section>}
  {error&&<div className="admin-error" role="alert">{error}</div>}
  <div className="gemini-grid">
   <section className="admin-panel gemini-card"><div className="gemini-card-title"><Search/><div><h2>Natural-language search</h2><p>Search only records allowed by your staff role.</p></div></div><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="e.g. Which shipments have unresolved customs or temperature issues?"/><Button disabled={!status?.configured||!search.trim()||!!busy} onClick={()=>run('search','ai-search',{query:search})}>{busy==='search'?'Searching…':'Search records'}</Button></section>
   <section className="admin-panel gemini-card"><div className="gemini-card-title"><FileSearch/><div><h2>Extract document fields</h2><p>Review extracted fields before using them anywhere.</p></div></div><NativeSelect value={doc} onChange={e=>setDoc(e.target.value)}><option value="">Choose a document</option>{catalog.documents.map(d=><option key={d.scope+d.id} value={d.scope+'|'+d.id} disabled={d.scope==='buyer'&&d.ai_allowed===false}>{d.scope==='buyer'?'Buyer':'Trade'} · {d.kind} · {d.name}</option>)}</NativeSelect>{selectedDoc?.scope==='buyer'&&!status?.buyer_document_ai_enabled&&<small>Buyer document AI is disabled until explicitly enabled by backend policy.</small>}<Button disabled={!status?.configured||!selectedDoc||!!busy} onClick={()=>selectedDoc&&run('extract','ai-extract',{scope:selectedDoc.scope,document_id:selectedDoc.id})}>{busy==='extract'?'Extracting…':'Extract into review'}</Button></section>
   <section className="admin-panel gemini-card"><div className="gemini-card-title"><Bot/><div><h2>Cross-document comparison</h2><p>Compare invoices, packing lists, certificates and shipment records.</p></div></div><NativeSelect value={order} onChange={e=>setOrder(e.target.value)}><option value="">Choose an order</option>{catalog.orders.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</NativeSelect><Button disabled={!status?.configured||!order||!!busy} onClick={()=>run('compare','ai-compare',{order_id:order})}>{busy==='compare'?'Comparing…':'Compare records'}</Button></section>
   <section className="admin-panel gemini-card"><div className="gemini-card-title"><AlertTriangle/><div><h2>Operational exceptions</h2><p>Summarize open risks and recommended human checks.</p></div></div><NativeSelect value={order} onChange={e=>setOrder(e.target.value)}><option value="">Choose an order</option>{catalog.orders.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</NativeSelect><Button disabled={!status?.configured||!order||!!busy} onClick={()=>run('exceptions','ai-exceptions',{order_id:order})}>{busy==='exceptions'?'Summarizing…':'Summarize exceptions'}</Button></section>
   <section className="admin-panel gemini-card gemini-wide"><div className="gemini-card-title"><MessageSquareText/><div><h2>Draft buyer communication</h2><p>Create a draft only. Sending remains a staff action.</p></div></div><div className="gemini-draft-controls"><NativeSelect value={order} onChange={e=>setOrder(e.target.value)}><option value="">Choose an order</option>{catalog.orders.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</NativeSelect><NativeSelect value={draftKind} onChange={e=>setDraftKind(e.target.value)}><option value="BUYER_MESSAGE">Buyer message</option><option value="COVER_LETTER">Document cover letter</option></NativeSelect></div><Textarea value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Optional instruction, tone or document context…"/><Button disabled={!status?.configured||!order||!!busy} onClick={()=>run('draft','ai-draft',{order_id:order,kind:draftKind,instructions})}>{busy==='draft'?'Drafting…':'Create draft'}</Button></section>
  </div>
  <Result value={result}/>
  <section className="admin-panel"><div className="admin-panel-heading"><div><h2>Prompt & response audit</h2><p className="admin-muted">Recent Gemini requests are retained in the existing AI jobs audit store. Inputs are redacted before audit storage.</p></div></div><div className="gemini-audit">{(state.jobs||[]).slice(0,12).map((j:Row)=><article key={j.id}><div><b>{j.kind.replaceAll('_',' ')}</b><small>{j.model} · {new Date(j.created).toLocaleString()}</small></div><span className={'admin-pill pill-'+j.status.toLowerCase()}>{j.status}</span></article>)}{!(state.jobs||[]).length&&<p className="admin-muted">No Gemini audit records yet.</p>}</div></section>
 </div>
}
