'use client';
/* oxlint-disable next/no-img-element */
import { useEffect, useState } from 'react';
import { AlertTriangle, Anchor, Box, Check, Clock3, Navigation, Pause, Play, Plus, RotateCcw, Ship, SkipForward, Snowflake, StepBack } from 'lucide-react';
import { Button } from '@/components/ui/button';
import ShipmentMap, { type Shipment } from '@/components/shipment-map';

// The control tower consumes server-shaped operational records.
// oxlint-disable-next-line typescript/no-explicit-any
type Row=Record<string,any>;
type Field={key:string;label:string;type?:string;options?:[string|number,string][];optional?:boolean};
const stamp=(value:string)=>value?new Date(value).toLocaleString():'Pending';
const options=(values:string[])=>values.map(value=>[value,value.replaceAll('_',' ')] as [string,string]);
const vesselPhoto=(name:string)=>name?.toLowerCase().includes('pacific')?'/vessels/blueharbor-pacific-realistic.png':'/vessels/blueharbor-atlas-realistic.png';

export default function ShippingControlTower({state,edit,act,busy}:{state:{orders:Row[];transport_shipments:Row[];shipping_schedule:{vessels:Row[];sailings:Row[]}};edit:(title:string,path:string,data:Row,fields:Field[])=>void;act:(path:string,data:unknown)=>Promise<boolean>;busy:boolean}){
 const shipments=state.transport_shipments||[];
 const sailings=state.shipping_schedule?.sailings||[];
 const [selected,setSelected]=useState(shipments[0]?.id||'');
 const shipment=shipments.find(item=>item.id===selected)||shipments[0];
 const [playing,setPlaying]=useState(false);
 const simulation=shipment?.simulation||{available:false,active:false,current_step:-1,total_steps:0,current:null,points:[]};
 useEffect(()=>{if(!playing||!shipment)return;const timer=setTimeout(()=>{if(simulation.current_step>=simulation.total_steps-1){setPlaying(false);return}void act('shipment-simulation',{shipment_id:shipment.id,mode:simulation.active?'STEP':'START'}).then(ok=>{if(!ok)setPlaying(false)})},1800);return()=>clearTimeout(timer)},[act,playing,shipment,simulation.active,simulation.current_step,simulation.total_steps]);
 const orderOptions=state.orders.filter(order=>!['CANCELLED','DELIVERED'].includes(order.status)).map(order=>[order.id,`${order.id} · ${order.product_name}`] as [string,string]);
 const activeExceptions=shipments.flatMap(item=>item.exceptions||[]).filter(item=>item.status!=='RESOLVED');
 const autoMatch=(orderId:string)=>edit('Match order to scheduled sailing','auto-allocate',{order_id:orderId},[{key:'order_id',label:'Order to allocate',options:orderOptions}]);
 const openPlan=()=>edit('Create carrier booking','shipment-plan',{order_id:orderOptions[0]?.[0],mode:'OCEAN',origin_port:'Cochin Port, India',origin_lat:9.968,destination_lat:25.2048,origin_lon:76.267,destination_lon:55.2708},[
  {key:'order_id',label:'Order',options:orderOptions},{key:'booking_reference',label:'Carrier booking reference',optional:true},{key:'mode',label:'Transport mode',options:options(['OCEAN','AIR','ROAD'])},{key:'carrier',label:'Carrier',optional:true},{key:'vessel',label:'Vessel',optional:true},{key:'voyage',label:'Voyage',optional:true},{key:'origin_port',label:'Origin port'},{key:'destination_port',label:'Destination port'},{key:'origin_lat',label:'Origin latitude',type:'decimal'},{key:'origin_lon',label:'Origin longitude',type:'decimal'},{key:'destination_lat',label:'Destination latitude',type:'decimal'},{key:'destination_lon',label:'Destination longitude',type:'decimal'},{key:'planned_departure',label:'Planned departure',type:'datetime-local',optional:true},{key:'planned_arrival',label:'Planned arrival',type:'datetime-local',optional:true},{key:'booking_cutoff',label:'Booking cut-off',type:'datetime-local',optional:true},{key:'documentation_cutoff',label:'Documentation cut-off',type:'datetime-local',optional:true},{key:'vgm_cutoff',label:'VGM cut-off',type:'datetime-local',optional:true},{key:'shipping_instructions',label:'Shipping instructions',type:'textarea',optional:true}
 ]);
 if(!shipment)return <section className="tower-empty"><Ship size={40}/><p className="admin-eyebrow">PHASE 3 / SHIPPING</p><h2>No order has entered a vessel journey yet</h2><p>The schedule engine matches an active order to an upcoming sailing by destination, departure, reefer capacity and available TEU.</p><Button disabled={!orderOptions.length} onClick={()=>autoMatch(orderOptions[0]?.[0])}><Navigation size={16}/>Match first order</Button></section>;
 const shipmentOptions=shipments.map(item=>[item.id,`${item.id} · ${item.origin_port} → ${item.destination_port}`] as [string,string]);
 const action=(kind:string)=>{
  const common={shipment_id:shipment.id};
  if(kind==='plan')return edit('Edit shipment plan','shipment-plan',{...shipment,order_id:shipment.orders?.[0]?.id},[{key:'order_id',label:'Assigned order',options:orderOptions.length?orderOptions:[[shipment.orders?.[0]?.id,shipment.orders?.[0]?.id]]},{key:'booking_reference',label:'Booking reference',optional:true},{key:'mode',label:'Mode',options:options(['OCEAN','AIR','ROAD'])},{key:'carrier',label:'Carrier',optional:true},{key:'vessel',label:'Vessel',optional:true},{key:'voyage',label:'Voyage',optional:true},{key:'origin_port',label:'Origin port'},{key:'destination_port',label:'Destination port'},{key:'origin_lat',label:'Origin latitude',type:'decimal'},{key:'origin_lon',label:'Origin longitude',type:'decimal'},{key:'destination_lat',label:'Destination latitude',type:'decimal'},{key:'destination_lon',label:'Destination longitude',type:'decimal'},{key:'planned_departure',label:'Planned departure',type:'datetime-local',optional:true},{key:'planned_arrival',label:'Planned arrival',type:'datetime-local',optional:true},{key:'booking_cutoff',label:'Booking cut-off',type:'datetime-local',optional:true},{key:'documentation_cutoff',label:'Documentation cut-off',type:'datetime-local',optional:true},{key:'vgm_cutoff',label:'VGM cut-off',type:'datetime-local',optional:true},{key:'shipping_instructions',label:'Instructions',type:'textarea',optional:true}]);
  if(kind==='leg')return edit('Add route or transshipment leg','shipment-leg',{...common,sequence:(shipment.legs?.length||0)+1,mode:'OCEAN'},[{key:'shipment_id',label:'Shipment',options:shipmentOptions},{key:'sequence',label:'Leg sequence',type:'number'},{key:'mode',label:'Mode',options:options(['OCEAN','AIR','ROAD'])},{key:'carrier',label:'Carrier',optional:true},{key:'vessel',label:'Vessel',optional:true},{key:'voyage',label:'Voyage',optional:true},{key:'origin_name',label:'Origin / transshipment port'},{key:'origin_lat',label:'Origin latitude',type:'decimal'},{key:'origin_lon',label:'Origin longitude',type:'decimal'},{key:'destination_name',label:'Destination port'},{key:'destination_lat',label:'Destination latitude',type:'decimal'},{key:'destination_lon',label:'Destination longitude',type:'decimal'},{key:'planned_departure',label:'Planned departure',type:'datetime-local',optional:true},{key:'planned_arrival',label:'Planned arrival',type:'datetime-local',optional:true}]);
  if(kind==='container')return edit('Container, seal and VGM','shipment-container',{...common,container_type:'40RF',stuffing_status:'PLANNED',tare_kg:0,verified_gross_kg:0,reefer_setpoint:-18},[{key:'shipment_id',label:'Shipment',options:shipmentOptions},{key:'container_number',label:'Container number'},{key:'container_type',label:'Container type'},{key:'seal_number',label:'Seal number',optional:true},{key:'stuffing_status',label:'Stuffing stage',options:options(['PLANNED','STUFFING','SEALED','GATE_IN','LOADED'])},{key:'stuffed_at',label:'Stuffed at',type:'datetime-local',optional:true},{key:'reefer_setpoint',label:'Reefer set point °C',type:'decimal',optional:true},{key:'ventilation_cbm',label:'Ventilation CBM',type:'decimal',optional:true},{key:'humidity_percent',label:'Humidity %',type:'decimal',optional:true},{key:'tare_kg',label:'Tare kg',type:'number'},{key:'verified_gross_kg',label:'Verified gross mass kg',type:'number'},{key:'vgm_method',label:'VGM method',optional:true},{key:'vgm_party',label:'VGM responsible party',optional:true},{key:'vgm_reference',label:'VGM reference',optional:true},{key:'vgm_at',label:'VGM recorded at',type:'datetime-local',optional:true}].filter(f=>f.key));
  if(kind==='customs')return edit('Update customs milestone','customs-milestone',{...common,kind:'ESANCHIT',status:'SUBMITTED'},[{key:'shipment_id',label:'Shipment',options:shipmentOptions},{key:'kind',label:'Milestone',options:options(['ESANCHIT','SHIPPING_BILL','LEO','EGM'])},{key:'reference',label:'ICEGATE / customs reference',optional:true},{key:'status',label:'Status',options:options(['PENDING','SUBMITTED','ACKNOWLEDGED','QUERY','HOLD','CLEARED','FILED'])},{key:'occurred_at',label:'Recorded time',type:'datetime-local',optional:true},{key:'note',label:'Evidence / note',type:'textarea',optional:true}]);
  if(kind==='event')return edit('Record transport event','transport-event',{...common,event_type:'ACTUAL'},[{key:'shipment_id',label:'Shipment',options:shipmentOptions},{key:'event_code',label:'Event code (e.g. DEPARTED)'},{key:'event_label',label:'Buyer-visible event label'},{key:'event_type',label:'Event basis',options:options(['ACTUAL','ESTIMATED'])},{key:'occurred_at',label:'Event time',type:'datetime-local'},{key:'location_name',label:'Location'},{key:'latitude',label:'Latitude',type:'decimal',optional:true},{key:'longitude',label:'Longitude',type:'decimal',optional:true},{key:'note',label:'Operational note',type:'textarea',optional:true}]);
  if(kind==='reefer')return edit('Record reefer reading','reefer-reading',{...common,container_id:shipment.containers?.[0]?.id,setpoint:shipment.containers?.[0]?.reefer_setpoint??-18},[{key:'shipment_id',label:'Shipment',options:shipmentOptions},{key:'container_id',label:'Container',options:(shipment.containers||[]).map((c:Row)=>[c.id,c.container_number])},{key:'setpoint',label:'Set point °C',type:'decimal'},{key:'supply_temperature',label:'Supply temperature °C',type:'decimal'},{key:'return_temperature',label:'Return temperature °C',type:'decimal'},{key:'humidity_percent',label:'Humidity %',type:'decimal',optional:true},{key:'alarm_code',label:'Alarm code',optional:true},{key:'occurred_at',label:'Reading time',type:'datetime-local'},{key:'note',label:'Note',type:'textarea',optional:true}]);
  return edit('Create operational exception','shipping-exception',{...common,severity:'WARNING',buyer_visible:1},[{key:'shipment_id',label:'Shipment',options:shipmentOptions},{key:'kind',label:'Exception type'},{key:'severity',label:'Severity',options:options(['INFO','WARNING','CRITICAL'])},{key:'title',label:'Title'},{key:'evidence',label:'Evidence',type:'textarea'},{key:'required_action',label:'Required action',type:'textarea'},{key:'owner',label:'Owner'},{key:'due_at',label:'Due at',type:'datetime-local',optional:true},{key:'buyer_visible',label:'Buyer visibility',options:[[1,'Visible to buyer'],[0,'Internal only']] }]);
 };
 return <div className="shipping-tower">
  <section className="tower-hero"><div><p className="admin-eyebrow">PHASE 3 / SHIPPING, CUSTOMS & LIVE TRACKING</p><h2>Vessel journeys, cargo windows and clearance.</h2><p>Each vessel follows its complete port rotation. Every order is matched to the loading and discharge calls that serve its buyer.</p></div><div className="tower-kpis"><span><b>{sailings.length}</b>available sailings</span><span><b>{activeExceptions.length}</b>open exceptions</span></div></section>
  <section className="tower-sailing-board"><header><div><p className="admin-eyebrow">AVAILABLE CONSOLIDATED SAILINGS</p><h3>Upcoming vessel journeys</h3></div><small>Schedule source is shown on every sailing</small></header><div>{sailings.map(s=><article key={s.id}><img src={vesselPhoto(s.vessel_name)} alt={s.vessel_name}/><div><span className={'event-source '+(s.schedule_source==='SAMPLE'?'staff':'carrier')}>{s.schedule_source==='SAMPLE'?'Schedule sample':'Carrier schedule'}</span><h4>{s.vessel_name}</h4><p>{s.carrier_name} · Voyage {s.voyage_number}</p><b>{s.rotation_name}</b><ol>{(s.calls||[]).map((call:Row)=><li key={call.id}><span>{call.sequence}</span>{call.port_name}<small>{call.country}</small></li>)}</ol><footer><span><b>{s.available_teu}</b> TEU remaining</span><span><b>{s.available_reefer}</b> reefer plugs</span><span>Starts {stamp(s.cycle_start)}</span></footer></div></article>)}</div></section>
  <div className="tower-toolbar"><label>Active shipment<select value={shipment.id} onChange={event=>{setPlaying(false);setSelected(event.target.value)}}>{shipments.map(item=><option key={item.id} value={item.id}>{item.id} · {item.vessel||'Vessel pending'}</option>)}</select></label><Button disabled={!orderOptions.length} onClick={()=>autoMatch(shipment.orders?.[0]?.id||orderOptions[0]?.[0])}><Navigation size={16}/>Rematch automatically</Button><details><summary>Operational overrides</summary><div><Button variant="outline" onClick={()=>action('plan')}>Edit plan</Button><Button variant="outline" onClick={openPlan}><Plus size={16}/>Manual plan</Button></div></details></div>
  <section className="simulation-lab"><header><div><p className="admin-eyebrow">POC TESTING TOOL</p><h3>Simulate this order’s vessel movement</h3><p>Move the ship through its fixed cargo journey. Every saved point appears in the buyer application as a clearly labelled simulation.</p></div><span className="simulation-badge">Testing only</span></header><div className="simulation-grid"><div className="simulation-controls"><div className="simulation-order"><img src={vesselPhoto(shipment.vessel)} alt="Representative vessel"/><div><small>{shipment.orders?.[0]?.id||shipment.id}</small><b>{shipment.orders?.[0]?.product_name||'Allocated cargo'}</b><span>{shipment.vessel} · {shipment.voyage}</span></div></div><div className="simulation-status"><span><b>{simulation.active?simulation.current_step+1:0}</b> / {simulation.total_steps} points</span><strong>{simulation.current?.label||'Simulation has not started'}</strong><small>{simulation.current?.location||'Choose Start or any journey point.'}</small><i><em style={{width:`${simulation.current?.progress||0}%`}}/></i></div><label>Jump to a journey point<select disabled={!simulation.available||busy} value={simulation.active?simulation.current_step:''} onChange={event=>void act('shipment-simulation',{shipment_id:shipment.id,mode:'JUMP',step:Number(event.target.value)})}><option value="">Choose a point</option>{simulation.points.map((point:Row)=><option key={point.index} value={point.index}>{point.number}. {point.label} · {point.location}</option>)}</select></label><div className="simulation-buttons"><Button variant="outline" disabled={!simulation.active||busy||simulation.current_step<=0} onClick={()=>void act('shipment-simulation',{shipment_id:shipment.id,mode:'PREVIOUS'})}><StepBack size={16}/>Previous</Button><Button disabled={!simulation.available||busy||simulation.current_step>=simulation.total_steps-1} onClick={()=>void act('shipment-simulation',{shipment_id:shipment.id,mode:simulation.active?'STEP':'START'})}><SkipForward size={16}/>{simulation.active?'Next movement':'Start'}</Button><Button variant="outline" disabled={!simulation.available||busy} onClick={()=>void act('shipment-simulation',{shipment_id:shipment.id,mode:'NEXT_PORT'})}><Anchor size={16}/>Next port</Button><Button variant="outline" disabled={!simulation.available||busy||simulation.current_step>=simulation.total_steps-1} onClick={()=>setPlaying(value=>!value)}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'Pause':'Auto play'}</Button><Button variant="outline" disabled={!simulation.available||busy} onClick={()=>void act('shipment-simulation',{shipment_id:shipment.id,mode:'START'})}><RotateCcw size={16}/>Restart</Button><Button variant="ghost" disabled={!simulation.active||busy} onClick={()=>{setPlaying(false);void act('shipment-simulation',{shipment_id:shipment.id,mode:'RESET'})}}>Reset test</Button></div></div><div className="simulation-map"><ShipmentMap shipment={shipment as Shipment}/></div></div></section>
  <section className="tower-map"><div className="tower-route"><span><Anchor size={17}/><small>ORIGIN</small><b>{shipment.origin_port}</b></span><i/><span><Navigation size={17}/><small>DESTINATION</small><b>{shipment.destination_port}</b></span><div><small>VESSEL / VOYAGE</small><b>{[shipment.vessel,shipment.voyage].filter(Boolean).join(' · ')||'Pending'}</b><small>ETA {stamp(shipment.planned_arrival)}</small></div></div></section>
  {!!shipment.rotation_calls?.length&&<section className="vessel-journey"><header><div><p className="admin-eyebrow">FULL VESSEL JOURNEY</p><h3>{shipment.sailing?.rotation_name}</h3></div><span>{shipment.sailing?.cycle_days} day rotation · IMO {shipment.sailing?.imo_number}</span></header><ol>{shipment.rotation_calls.map((call:Row)=>{const load=call.id===shipment.load_call_id,discharge=call.id===shipment.discharge_call_id;const cargo=call.sequence>=(shipment.rotation_calls.find((x:Row)=>x.id===shipment.load_call_id)?.sequence||0)&&call.sequence<=(shipment.rotation_calls.find((x:Row)=>x.id===shipment.discharge_call_id)?.sequence||0);return <li className={(cargo?'cargo-window ':'')+(load?'load-call ':discharge?'discharge-call ':'')} key={call.id}><span>{call.sequence}</span><div><b>{call.port_name}</b><small>{call.country}</small></div><time>{stamp(call.estimated_arrival)}</time>{load?<em>Your cargo loads</em>:discharge?<em>Your cargo discharges</em>:null}</li>})}</ol><p className="journey-note">The highlighted section is this order cargo journey. Muted calls are the wider vessel rotation before loading or after discharge.</p></section>}
  {!!activeExceptions.filter(item=>item.shipment_id===shipment.id).length&&<section className="tower-alerts"><h3><AlertTriangle size={18}/>Actions requiring attention</h3>{activeExceptions.filter(item=>item.shipment_id===shipment.id).map(item=><article key={item.id}><b>{item.title}</b><p>{item.required_action}</p><span>{item.severity} · {item.owner}</span></article>)}</section>}
  <div className="tower-actions">{[['leg','Route leg',Navigation],['container','Container & VGM',Box],['customs','Customs gate',Check],['event','Transport event',Clock3],['reefer','Reefer reading',Snowflake],['exception','Exception',AlertTriangle]].map(([key,label,Icon])=><button key={key as string} onClick={()=>action(key as string)}><Icon size={19}/><span><b>{label as string}</b><small>Add or update</small></span></button>)}</div>
  <div className="tower-columns"><section className="tower-panel"><h3>Customs clearance</h3>{['ESANCHIT','SHIPPING_BILL','LEO','EGM'].map(kind=>{const item=(shipment.customs||[]).find((row:Row)=>row.kind===kind);return <article className="customs-gate" key={kind}><span className={item?.status==='CLEARED'||item?.status==='FILED'?'complete':''}>{item?<Check size={14}/>:null}</span><div><b>{kind.replaceAll('_',' ')}</b><small>{item?`${item.status} · ${item.reference||'reference pending'}`:'Pending'}</small></div><em>{item?.source_type==='STAFF'?'Staff entered':item?.source_type?'Carrier reported':'Awaiting'}</em></article>})}</section>
  <section className="tower-panel"><h3>Containers and cold chain</h3>{(shipment.containers||[]).map((container:Row)=>{const reading=(shipment.reefer||[]).find((row:Row)=>row.container_id===container.id);return <article className="container-card" key={container.id}><Box size={20}/><div><b>{container.container_number} · {container.container_type}</b><small>Seal {container.seal_number||'pending'} · VGM {container.verified_gross_kg||0} kg</small><span className={reading?.severity&&reading.severity!=='NORMAL'?'temperature-warning':''}>{reading?`${reading.supply_temperature}°C · ${reading.severity}`:`Set point ${container.reefer_setpoint??'—'}°C`}</span></div></article>})}{!shipment.containers?.length&&<p className="admin-muted">No container has been assigned.</p>}</section></div>
  <section className="tower-panel event-ledger"><h3>Event ledger</h3>{[...(shipment.events||[])].reverse().map((event:Row)=><article key={event.id}><time>{stamp(event.occurred_at)}</time><span className={'event-source '+event.source_type?.toLowerCase()}>{event.source_type==='STAFF'?'Staff entered':'Carrier reported'}</span><div><b>{event.event_label}</b><p>{event.location_name}{event.note?' · '+event.note:''}</p></div></article>)}{!shipment.events?.length&&<p className="admin-muted">No transport events recorded.</p>}</section>
 </div>;
}



